# Generated by Django 5.2.5 on 2025-09-04 06:51

import canvas_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.CharField()),
                ('name', models.CharField()),
                ('calendar', models.JSONField(default=dict, encoder=canvas_api.models.PrettyJSONEncoder)),
                ('time_zone', models.CharField()),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('unlock_at', models.DateTimeField(null=True)),
                ('lock_at', models.DateTimeField(null=True)),
                ('points_possible', models.IntegerField()),
                ('grade_group_students_individually', models.BooleanField(default=False)),
                ('allowed_attempts', models.IntegerField()),
                ('has_submitted_submissions', models.BooleanField(default=False)),
                ('course_id', models.IntegerField()),
                ('grading_type', models.CharField(choices=[('pass_fail', 'Pass fail'), ('percent', 'Percent'), ('letter_grade', 'Letter grade'), ('gpa_scale', 'GPA scale'), ('points', 'Points'), ('not_graded', 'Not graded')], default='percent')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas_api.course')),
            ],
        ),
    ]
