# Generated by Django 5.2.5 on 2025-09-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
