# Generated by Django 5.2.5 on 2025-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_api', '0003_assignment_assignment_id_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='has_submitted_submissions',
            new_name='is_submitted',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allowed_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.IntegerField(null=True),
        ),
    ]
