# Generated by Django 5.2.5 on 2025-09-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_api', '0004_rename_has_submitted_submissions_assignment_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
