# Generated by Django 5.2.5 on 2025-09-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_api', '0005_alter_assignment_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
